[versions]
androidGradlePlugin = '7.2.2'
kotlin = '1.6.21'
kotlinCoroutines = { strictly = '1.6.0-native-mt' }
ktor = '2.0.0'
mokoResources = "0.20.1"
ktlintRules = '1.0.0'
adapters = '1.1.1'
sentry = '5.7.3'
fragment = '1.4.1'
flipper = '0.148.0'

kitPresentationRedux = '1.3.1'

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "10.2.0" }
plugin-gradleVersionUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.39.0" }
plugin-buildKonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version = "0.13.3" }
plugin-mokoResources = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResources" }

kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.2" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kit-model = { module = "ru.nobird.app.core:model", version = "1.0.8" }
kit-presentation-redux = { module = "ru.nobird.app.presentation:presentation-redux", version.ref = "kitPresentationRedux" }
kit-presentation-reduxCoroutines = { module = "ru.nobird.app.presentation:presentation-redux-coroutines", version.ref = "kitPresentationRedux" }
kit-view-ui = { module = "ru.nobird.android.view:ui", version = '1.1.0' }
kit-view-redux = { module = "ru.nobird.android.view:redux", version = "1.3.0" }
kit-view-injection = { module = "ru.nobird.android.view:injection", version = "1.1.0" }
kit-view-navigation = { module = "ru.nobird.android.view:navigation", version = "1.1.0" }
kit-ui-adapters = { module = "ru.nobird.android.ui:adapters", version.ref = "adapters" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version = "0.8.1" }

android-ui-material = { module = "com.google.android.material:material", version = "1.4.0" }
android-ui-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.0" }
android-ui-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.2" }
android-ui-core-ktx = { module = "androidx.core:core-ktx", version = "1.3.0" }
android-ui-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
android-ui-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
android-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.4.1" }
android-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.4.0" }

android-test-junit = { module = "junit:junit", version = "4.13.2" }
android-test-runner = { module = "androidx.test:runner", version = "1.4.0" }
android-test-robolectric = { module = "org.robolectric:robolectric", version = "4.7.1" }

gms-services = { module = "com.google.android.gms:play-services-base", version = "17.6.0" }
gms-login = { module = "com.google.android.gms:play-services-auth", version = "19.0.0" }
viewbinding = { module = "com.github.kirich1409:viewbindingpropertydelegate", version = "1.5.6" }

mokoResources-main = { module = "dev.icerock.moko:resources", version.ref = "mokoResources" }
mokoResources-test = { module = "dev.icerock.moko:resources-test", version.ref = "mokoResources" }

ktlintRules = { module = "ru.nobird.android.ktlint:rules", version.ref = "ktlintRules" }

android-security = { module = "androidx.security:security-crypto", version = "1.1.0-alpha03" }
android-material-progress-bar = { module = "me.zhanghai.android.materialprogressbar:library", version = "1.6.1" }
android-sentry = { module = "io.sentry:sentry-android", version.ref = "sentry" }
android-sentry-fragment = { module = "io.sentry:sentry-android-fragment", version.ref = "sentry" }
android-flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
android-flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
android-soloader = { module = "com.facebook.soloader:soloader", version = "0.10.1" }
android-parcelable = { module = "com.chrynan.parcelable:parcelable-core", version = "0.4.1" }

android-reactivex-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version = "2.1.0" }
android-reactivex-rxjava = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.5" }
android-reactivex-rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version = "2.3.0" }
android-coil = { module = "io.coil-kt:coil", version = "2.1.0" }
android-coil-svg = { module = "io.coil-kt:coil-svg", version = "2.1.0" }
android-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0-beta02" }
android-timepicker = { module = "io.github.ShawnLin013:number-picker", version = "2.4.13" }

android-desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

[bundles]
ktor-common = ['ktor-core', 'ktor-serialization', 'ktor-logging', 'ktor-contentNegotiation', 'ktor-serialization-json']
android-test = ['android-test-junit', 'android-test-runner', 'android-test-robolectric']

[plugins]
sentry-androidGradle = { id = "io.sentry.android.gradle", version = "3.0.1" }